jenkins:
  systemMessage: "Configured automatically with JCasC plugin"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  labelString: flyweight
  mode: EXCLUSIVE
  numExecutors: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 2
  nodes:
  - permanent:
      labelString: "local linux"
      launcher:
        jnlp:
          workDirSettings:
            disabled: true
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
            workDirPath: "/tmp"
      name: "local"
      numExecutors: 2
      remoteFS: "/tmp"
      retentionStrategy: "always"
unclassified:
  openTelemetry:
    authentication: "noAuthentication"
    endpoint: "http://otel-collector:4317"
    exportOtelConfigurationAsEnvironmentVariables: true  # Note that OpenTelemetry credentials, if configured, will be exposed as environment variables
    observabilityBackends:
    - elastic:
        displayKibanaDashboardLink: true
        kibanaBaseUrl: "http://kibana:5601"
        name: "Elastic Observability"
    - jaeger:
        jaegerBaseUrl: "http://jaeger:16686"
        name: "Jaeger"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: GitHub user @${github_username} User + Personal Access Token
              id: GitHubUserAndToken
              password: ${github_personal_access_token}
              scope: GLOBAL
              username: ${github_username}
          - usernamePassword:
              description: Docker user @${docker_user} User + Token
              id: DockerUserAndToken
              password: ${docker_token}
              scope: GLOBAL
              username: ${docker_user}
          - usernamePassword:
              description: Docker user @${docker_user} User + Token
              id: docker.io
              password: ${docker_token}
              scope: GLOBAL
              username: ${docker_user}
          - string:
              description: snyk.io token.
              id: snyk.io
              scope: GLOBAL
              secret: ${snyk}

jobs:
  - file: "/var/jenkins_home/config/folder.dsl"
  - file: "/var/jenkins_home/config/antifraud.dsl"
  - file: "/var/jenkins_home/config/deploy-canary.dsl"
  - file: "/var/jenkins_home/config/deploy-environment.dsl"
  - file: "/var/jenkins_home/config/rollback.dsl"
  - file: "/var/jenkins_home/config/progressive-deployment.dsl"
  - file: "/var/jenkins_home/config/quality-gate.dsl"
