---
- name: Deploy demo app
  hosts: localhost
  connection: local
  vars:
    default_container_image: docker.io/v1v1v/anti-fraud
    version: 0.0.1-SNAPSHOT

  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ default_container_image }}:{{ version }}"
        source: pull

    - name: Spin up antifraud services
      docker_container:
        name: "{{ item.name }}"
        image: "{{ default_container_image }}:{{ version }}"
        state: started
        recreate: yes
        ports:
          - "{{ item.port }}:8080"
        networks:
          - name: infra_default
        env:
          OTEL_SERVICE_NAME: "{{ item.name }}"
      loop:
        - { name: "antifraud-01", port: '28080' }
        - { name: "antifraud-02", port: '28081' }

    - name: Healtcheck URL
      uri:
        url: "http://{{ item.name }}.example.com:{{ item.port }}/ecommerce"
      retries: 5
      delay: 2
      register: _result
      until: _result.status == 200
      loop:
        - { name: "antifraud-01", port: '28080' }
        - { name: "antifraud-02", port: '28081' }

    - name: Update annotation
      uri:
        url: "http://kibana:5601/api/apm/services/{{ item.name }}/annotation"
        method: POST
        body_format: json
        body: "{\"@timestamp\": \"{{ ansible_date_time.iso8601 }}\",\"service\": {\"version\": \"{{ version }}\"},\"message\": \"Deployment {{ version }}\"}"
        headers:
          kbn-xsrf: true
      loop:
        - { name: "antifraud-01", port: '28080' }
        - { name: "antifraud-02", port: '28081' }
