---
- name: Deploy app
  hosts: localhost
  connection: local
  vars:
    port_container: 28082

  tasks:
    - name: Healtcheck URL is reachable from this host
      uri:
        url: "http://localhost:{{ port_container }}/healthcheck"
      retries: 30
      delay: 1
      register: _result
      until: _result.status == 200
      ignore_errors: yes
