---
- name: Deploy app
  hosts: localhost
  connection: local
  vars:
    default_container_name: anti-fraud-02
    default_container_image: docker.io/v1v1v/anti-fraud:latest

  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        registry_url: https://index.docker.io/v1/

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        ports:
          - "28081:8080"
        networks:
          - name: infra_default
