---
- name: Deploy app
  hosts: localhost
  connection: local
  vars:
    default_container_name: anti-fraud
    default_container_image: docker.io/v1v1v/anti-fraud:latest

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        ports:
          - "28080:8080"
# TODO: healtcheck with APM
